config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :turmas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/turma.rb
class Turma < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_turma, only: [:show, :edit, :update, :destroy]

  # GET /turmas
  # GET /turmas.json
  def index
    @turmas = Turma.all
  end

  # GET /turmas/1
  # GET /turmas/1.json
  def show
  end

  # GET /turmas/new
  def new
    @turma = Turma.new
  end

  # GET /turmas/1/edit
  def edit
  end

  # POST /turmas
  # POST /turmas.json
  def create
    @turma = Turma.new(turma_params)

    respond_to do |format|
      if @turma.save
        format.html { redirect_to @turma, notice: 'Turma was successfully created.' }
        format.json { render :show, status: :created, location: @turma }
      else
        format.html { render :new }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turmas/1
  # PATCH/PUT /turmas/1.json
  def update
    respond_to do |format|
      if @turma.update(turma_params)
        format.html { redirect_to @turma, notice: 'Turma was successfully updated.' }
        format.json { render :show, status: :ok, location: @turma }
      else
        format.html { render :edit }
        format.json { render json: @turma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turmas/1
  # DELETE /turmas/1.json
  def destroy
    @turma.destroy
    respond_to do |format|
      format.html { redirect_to turmas_url, notice: 'Turma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turma
      @turma = Turma.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turma_params
      params.require(:turma).permit(:nome, :inicio, :fim, :horas)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/turmas_helper.rb
module TurmasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClassGeek</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <!-- Navigation Bar -->
      
      
<nav class="navbar navbar-toggleable-sm navbar-inverse bg-inverse">
  <div class="container">
    <%= link_to "ClassGeek", root_path, class: "navbar-brand" %>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Turmas", turmas_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to "Contato", "#", class: "nav-link" %></li>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item"><%= link_to "Sair", destroy_user_session_path, method: :delete, class: "btn btn-danger" %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Entrar", new_user_session_path, class: "btn btn-success" %>|</li>
        <li class="nav-item"><%= link_to "Cadastrar", new_user_registration_path, class: "btn btn-primary" %></li>
      <% end %>
    </ul>
  </div>
</nav>
      
      
      
      <% flash.each do |name, message| %>
        <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
      <% end %>
      
      
      
      

    <!-- Page Content -->
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
    
    <% if user_signed_in? %>
    
        <h1 class="display-3">Bem-vindo ao ClassGeek - Você está DENTRO do sistema!</h1>
    
    <% else %>
    
        <h1 class="display-3">Bem-vindo ao ClassGeek - Cadastre-se Abaixo!</h1>
    
    
    
          <p class="lead">Teste!!!.</p>
          <hr class="my-4">
          <p>Teste!!!!.</p>
          <p class="lead">
              <%= link_to "Cadastre-se", new_user_registration_path, class: "btn btn-primary btn-lg" %>

          </p>
    
    <% end %> 
    
    
    
</div>

app/views/turmas/_form.html.erb
<%= form_for(turma) do |f| %>
  <% if turma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turma.errors.count, "error") %> prohibited this turma from being saved:</h2>

      <ul>
      <% turma.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :inicio %>
    <%= f.datetime_select :inicio %>
  </div>

  <div class="field">
    <%= f.label :fim %>
    <%= f.datetime_select :fim %>
  </div>

  <div class="field">
    <%= f.label :horas %>
    <%= f.text_field :horas %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/turmas/edit.html.erb
<h1>Editing Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Show', @turma %> |
<%= link_to 'Back', turmas_path %>

app/views/turmas/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Turmas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Inicio</th>
      <th>Fim</th>
      <th>Horas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turmas.each do |turma| %>
      <tr>
        <td><%= turma.nome %></td>
        <td><%= turma.inicio %></td>
        <td><%= turma.fim %></td>
        <td><%= turma.horas %></td>
        <td><%= link_to 'Show', turma %></td>
        <td><%= link_to 'Edit', edit_turma_path(turma) %></td>
        <td><%= link_to 'Destroy', turma, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turma', new_turma_path %>

app/views/turmas/new.html.erb
<h1>New Turma</h1>

<%= render 'form', turma: @turma %>

<%= link_to 'Back', turmas_path %>

app/views/turmas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @turma.nome %>
</p>

<p>
  <strong>Inicio:</strong>
  <%= @turma.inicio %>
</p>

<p>
  <strong>Fim:</strong>
  <%= @turma.fim %>
</p>

<p>
  <strong>Horas:</strong>
  <%= @turma.horas %>
</p>

<%= link_to 'Edit', edit_turma_path(@turma) %> |
<%= link_to 'Back', turmas_path %>